services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $adminFirewallName: "%kunstmaan_admin.admin_firewall_name%"

  _instanceof:
    Kunstmaan\AdminBundle\Helper\Menu\MenuAdaptorInterface:
      tags: [kunstmaan_admin.menu.adaptor]

  Kunstmaan\CookieBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Repository,Tests,Controller,Features,Resources}'

  Kunstmaan\CookieBundle\Controller\:
    resource: '../../Controller/*'
    autowire: true
    public: true
